import { STATUS } from "./status";

export const dummyFiles = [
  {
    id: 1,
    tipe: "Skripsi",
    judul: "Efektivitas TF-IDF dan Cosine Similarity untuk Deteksi Plagiarisme",
    penulis: "Syauqi Zainun Nauval",
    nim: "202012345678",
    prodi: "IF",
    fakultas: "FTI",
    tahun: 2024,
    pembimbing: "Dr. Ahmad, M.Kom",
    tanggalUpload: "01 Juni 2024",
    versi: 1,
    keywords: ["TF-IDF", "Cosine Similarity", "Plagiarisme"],
    abstrak: "Penelitian ini membahas deteksi kemiripan judul skripsi menggunakan TF-IDF dan Cosine Similarity.",
    status: STATUS.DITERIMA,
    pdfUrl: "/plagiarisme_tfidf_cosine.pdf",
  },
  {
    id: 2,
    tipe: "Skripsi",
    judul: "Aplikasi Penjadwalan Kuliah",
    penulis: "Siti Aminah",
    nim: "202012345679",
    prodi: "SI",
    fakultas: "FTI",
    tahun: 2023,
    pembimbing: "Dr. Budi, M.Kom",
    tanggalUpload: "15 Agustus 2023",
    versi: 1,
    keywords: ["penjadwalan", "kuliah"],
    abstrak: "Pengembangan aplikasi penjadwalan kuliah berbasis web.",
    status: STATUS.DITERIMA,
    pdfUrl: "/jadwal_kuliah.pdf",
  },
  {
    id: 3,
    tipe: "Skripsi",
    judul: "Analisis Sistem Informasi Akademik",
    penulis: "Syauqi Zainun Nauval",
    nim: "202012345678",
    prodi: "IF",
    fakultas: "FTI",
    tahun: 2024,
    pembimbing: "Dr. Ahmad, M.Kom",
    tanggalUpload: "10 Juli 2024",
    versi: 1,
    keywords: ["SIAKAD", "Web"],
    abstrak: "Dokumen ini masih dalam proses verifikasi oleh admin.",
    status: STATUS.PENDING,
    pdfUrl: "/plagiarisme_tfidf_cosine.pdf",
  },
  {
    id: 4,
    tipe: "Laporan KP",
    judul: "Sistem Informasi Keuangan",
    penulis: "Dewi Lestari",
    nim: "202012345681",
    prodi: "SI",
    fakultas: "FTI",
    tahun: 2024,
    pembimbing: "Dr. Rina, M.Kom",
    tanggalUpload: "01 September 2024",
    versi: 2,
    keywords: ["keuangan", "sistem informasi"],
    abstrak: "Laporan KP mengenai sistem informasi keuangan.",
    status: STATUS.DITOLAK,
    alasanPenolakan: "Dokumen tidak sesuai format pedoman KP.",
    pdfUrl: "/sistem_keuangan.pdf",
  },
  {
    id: 5,
    tipe: "Laporan KP",
    judul: "Aplikasi Mobile Perpustakaan",
    penulis: "Ahmad Fauzi",
    nim: "202012345682",
    prodi: "IF",
    fakultas: "FTI",
    tahun: 2025,
    pembimbing: "Dr. Hendra, M.Kom",
    tanggalUpload: "20 Agustus 2024",
    versi: 1,
    keywords: ["mobile", "perpustakaan"],
    abstrak: "Laporan KP pengembangan aplikasi mobile perpustakaan.",
    status: STATUS.DITERIMA,
    pdfUrl: "/mobile_library.pdf",
  },
];
